name: Demigod Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify Files
        run: |
          ls -la
          test -f Dockerfile
          test -f index.html

  build:

    runs-on: ubuntu-latest

    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t demigod:test .

  test:

    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build Again
        run: |
          docker build -t demigod:test .

      - name: Start Container
        run: |
          docker run -d \
          --name demo \
          -p 8080:80 \
          demigod:test

      - name: Verify Website
        run: |
          sleep 5
          curl http://localhost:8080

  deploy:

    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Deployment Simulation
        run: |
          echo "Deploying Application"
